### ISSUE TITLE
Events?

### ISSUE THREAD

**Issue by andresvia** [cpuguy83/go-docker#11]
I'm creating a container and immediately inspecting it.

sometimes `inspectOut.NetworkSettings.Ports[portDefinition]` has the host port mapping as a list, but sometimes the map has the item, but is an empty list, I can probably implement a waiter, but maybe If I can check the events for a container I could delay the inspection until the container network is connected.

**Comment by cpuguy83** [comment]
Events added in fc314252460f2de84c507524c7f0564a72afb99e
