### ISSUE TITLE
I want to use this client instead of the official Client.RegistryLogin

### ISSUE THREAD

**Issue by andresvia** [cpuguy83/go-docker#9]
For all the arguments included in the readme I want to use this package instead of the official.

But I can't replace this function.

https://pkg.go.dev/github.com/moby/moby@v20.10.21+incompatible/client#Client.RegistryLogin

It'll be great to have it.

Thanks for the package.

**Comment by cpuguy83** [comment]
Added in ecc60f644180010e964100b47a8185fad51066db
